### ISSUE TITLE
Add test checking for className="undefined" on all pages

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2500]
This is a pretty easy mistake to make (see https://github.com/responsible-ai-collaborative/aiid/pull/2499) and not a hard one to check automatically.

In the meantime I'll just add this userstyle to my browser. Won't miss it that way:

```css
@-moz-document regexp(".*://(localhost:8000|incidentdatabase.ai|staging-aiid.netlify.app).*") {
    .undefined {
      animation: 1s linear infinite spin;
    }
    @keyframes spin {
      0% { color: red; rotate: 0deg; }
      50% { color: orange }
      100% { color: red; rotate: 360deg; }
    }
}
```
